version: "3.5"
name: "collab-nest-services"
services:
  db:
    image: "postgres"
    restart: always
    container_name: collab-nest-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "collab-nest"
      POSTGRES_PASSWORD: "password"
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "8010:5432"

volumes:
  database-data:
