import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { notFound } from "next/navigation";

const locales = ["en"];


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params : {locale}
}: Readonly<{
  children: React.ReactNode;
  params : {locale : string};
}>) {

  const isValidLocale = locales.some((curr) => curr === locale);
  if(!isValidLocale) notFound();

  return (
    <html lang={locale}>
      
      <body
        className={` antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        
      </body>
    </html>
  );
}
